#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# Author: graypawn (choi.pawn @gmail.com)
# Created: 2017-03-21
MOUNT_DIR=/mnt/arch
HOST="$1"
SYSLINUX_DIR=$MOUNT_DIR/boot/syslinux/
SYSLINUX_CFG=$SYSLINUX_DIR/syslinux.cfg
THIS_HOME_DIR=/home/"$(users)"
DOTFILES_DIR=../

# PARAMETER
if [ $# -ne 1 ]
then
    echo "Usage: $0 HOSTNAME"
    exit 1
fi

# MAIN
source ./profile/$HOST.cfg 2>/dev/null \
    || { echo "Failed to read profile"; exit 1; }

[[ -z "$ROOT_UUID" || -z "$TYPE" || -z "$USERNAME" ]] \
    && { echo "Failed to read necessary value"; exit 1; }

# ROOT_UUID
mkdir -p $MOUNT_DIR
mount -U $ROOT_UUID $MOUNT_DIR || exit 1

# HOME_UUID
if [ -n "$HOME_UUID" ]
then
    mkdir -p $MOUNT_DIR/home
    mount -U $HOME_UUID $MOUNT_DIR/home
fi

# BOOT_UUID
if [ -n "$BOOT_UUID" ]
then
    mkdir -p $MOUNT_DIR/boot
    mount -U $BOOT_UUID $MOUNT_DIR/boot
fi

# COPY FILES
cp ./chroot $MOUNT_DIR
cp ./profile/$HOST.sh $MOUNT_DIR

if [[ -z $SYSLINUX_CFG ]] || [[ ! -r $SYSLINUX_CFG ]]
then
    mkdir -p $SYSLINUX_DIR
    cp /boot/syslinux/splash.png $SYSLINUX_DIR/
    sed "s/{UUID}/$ROOT_UUID/g" ./syslinux.cfg > \
        $SYSLINUX_CFG
fi

mkdir -p -m 700 $MOUNT_DIR/root/.ssh
find $THIS_HOME_DIR/.ssh -name "*.rsa" -o -name "*.pub" -o -name "config" \
    | xargs cp -t $MOUNT_DIR/root/.ssh

# INSTALL BASE SYSTEM
pacstrap $MOUNT_DIR base base-devel syslinux openssh sudo git emacs
genfstab -U -p $MOUNT_DIR >> $MOUNT_DIR/etc/fstab

arch-chroot $MOUNT_DIR ./chroot "$HOST" "$USERNAME" "$TYPE"
rm $MOUNT_DIR/chroot
rm -r $MOUNT_DIR/root/.ssh

# RUN THE SCRIPT FOR HOST
arch-chroot $MOUNT_DIR ./$HOST.sh
rm $MOUNT_DIR/$HOST.sh

# FINISH
umount -R $MOUNT_DIR
echo INSTALL COMPLETE
